language: haskell
addons:
  apt:
    packages:
      - libgl1-mesa-dev
      - libglu1-mesa-dev
      - freeglut3-dev
      - libpulse-dev
      - libblas-dev
      - liblapack-dev
    sources:
      - sourceline: 'ppa:hvr/ghc'
    packages:
      - libgl1-mesa-dev
      - libglu1-mesa-dev
      - freeglut3-dev
      - libpulse-dev
      - libblas-dev
      - liblapack-dev
cache:
  directories:
    - $HOME/.cabal
ghc:
  - '8.10'
  - '8.8.3'
  - '8.6'
script:
  - cabal new-build all --enable-tests
  - cabal new-test all --enable-tests
  - git fetch origin master:origin/master && git rebase origin/master --exec "cabal new-build all --enable-tests"
install: skip
